apiVersion: v1
kind: Service
metadata:
  annotations:
    dlt.service.type: loader
    kompose.cmd: kompose convert -f helm-axies.yml -c --with-kompose-annotation=true
      --controller deployment
    kompose.controller.type: deployment
    kompose.image-pull-policy: Always
    kompose.version: 1.26.1 (a9d05d509)
    kompose.volume.size: 1Gi
    kompose.volume.storage-class-name: gp2
    prometheus.io/path: /
    prometheus.io/port: '8000'
    prometheus.io/scrape: 'true'
  creationTimestamp: null
  labels:
    io.kompose.service: axie-loader
  name: axie-loader
spec:
  ports:
  - name: '8000'
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: axie-loader
status:
  loadBalancer: {}
