apiVersion: v1
data:
  GCP__CLIENT_EMAIL: {{ .Values.envs.bigqueryCredentialsEnv.gcpClientEmail | quote
    }}
  GCP__HTTP_TIMEOUT: {{ .Values.envs.bigqueryCredentialsEnv.gcpHttpTimeout | quote
    }}
  GCP__PROJECT_ID: {{ .Values.envs.bigqueryCredentialsEnv.gcpProjectId | quote }}
  GCP__RETRY_DEADLINE: {{ .Values.envs.bigqueryCredentialsEnv.gcpRetryDeadline |
    quote }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: axie-extractor-envs-bigquery-credentials-env
  name: envs-bigquery-credentials-env
