apiVersion: v1
data:
  PG__DBNAME: {{ .Values.envs.redshiftCredentialsEnv.pgDbname | quote }}
  PG__HOST: {{ .Values.envs.redshiftCredentialsEnv.pgHost | quote }}
  PG__PASSWORD: {{ .Values.envs.redshiftCredentialsEnv.pgPassword | quote }}
  PG__USER: {{ .Values.envs.redshiftCredentialsEnv.pgUser | quote }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: axie-extractor-envs-redshift-credentials-env
  name: envs-redshift-credentials-env
