apiVersion: v1
data:
  gcp--private-key: {{ .Values.secrets.gcpPrivateKey | b64enc | default "''" }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gcp--private-key
  name: gcp--private-key
type: Opaque
