apiVersion: v1
data:
  pg--password: {{ .Values.secrets.pgPassword | b64enc | default "''" }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pg--password
  name: pg--password
type: Opaque
