apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pipeline-volume
  name: pipeline-volume
spec:
  accessModes: 

    {{ toYaml .Values.volumes.accessModes | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.volumes.pipelineVolume.storage  }}
  storageClassName: {{ .Values.volumes.storageClassName }}
status: {}
