envs:
  bigqueryCredentialsEnv:
    gcpClientEmail: set-me-up
    gcpHttpTimeout: '20.0'
    gcpProjectId: set-me-up
    gcpRetryDeadline: '300.0'
  commonEnv:
    clientType: bigquery
    defaultDataset: axies_1
    exitOnException: 'False'
    isDevelopmentConfig: 'False'
    isSingleRun: 'False'
    logLevel: DEBUG
    prometheusPort: '8000'
    sentryDsn: ''
  extractorEnv:
    runSleep: '60.0'
    runSleepIdle: '60.0'
  loaderEnv:
    runSleep: '1'
    runSleepIdle: '1'
  redshiftCredentialsEnv:
    pgDbname: set-me-up
    pgHost: set-me-up
    pgPassword: set-me-up
    pgUser: set-me-up
images:
  pipelineImage: scalevector/dlt-axie-infinity-demo:1.0.0
nodeSelector: {}
pods:
  axieExtractorPod:
    terminationGracePeriodSeconds: 320
  axieLoaderPod:
    terminationGracePeriodSeconds: 320
secrets:
  gcpPrivateKey: set-me-up
  pgPassword: ''
volumes:
  accessModes:
  - ReadWriteOnce
  pipelineVolume:
    storage: 1Gi
  storageClassName: gp2
