version: "3.8"
# base service definition derived by all environments
x-prometheus-port: &prometheus-port
  - "8000"

x-pipeline-image: &pipeline-image scalevector/dlt-axie-infinity-demo:1.0.0

services:
  axie-extractor:
    restart: "always"
    image: *pipeline-image
    labels:
      kompose.controller.type: deployment
      kompose.volume.size: 1Gi
      kompose.image-pull-policy: Always
      kompose.volume.storage-class-name: gp2
      prometheus.io/scrape: "true"
      prometheus.io/path: "/"
      prometheus.io/port: 8000
      dlt.service.type: extractor
    command: sh -c 'while python axies.py; do echo "Running....."; done'
    volumes:
      - pipeline_volume:/var/local/pipeline
    ports: *prometheus-port
    env_file:
      - envs/common.env
      - envs/extractor.env
      - envs/bigquery-credentials.env
      - envs/redshift-credentials.env
    secrets:
      - gcp--private-key
      - pg--password

  axie-loader:
    restart: "always"
    image: *pipeline-image
    labels:
      kompose.controller.type: deployment
      kompose.volume.size: 1Gi
      kompose.image-pull-policy: Always
      kompose.volume.storage-class-name: gp2
      prometheus.io/scrape: "true"
      prometheus.io/path: "/"
      prometheus.io/port: 8000
      dlt.service.type: loader
    command: sh -c 'while python axies_load.py; do echo "Running....."; done'
    volumes:
      - pipeline_volume:/var/local/pipeline
    ports: *prometheus-port
    env_file:
      - envs/common.env
      - envs/loader.env
      - envs/bigquery-credentials.env
      - envs/redshift-credentials.env
    secrets:
      - gcp--private-key
      - pg--password

volumes:
  pipeline_volume:

secrets:
  gcp--private-key:
    file: secrets/gcp--private-key
  pg--password:
    file: secrets/pg--password